self.addEventListener('install', function(e) {
    e.waitUntil(
        caches.open('learntotypepwa').then(function(cache) {
            return cache.addAll([
                '/learntotype',
                '/learntotype/Hebrew/index.html',
                '/learntotype/Hebrew/words.js',
                '/learntotype/favicon.ico',
                '/learntotype/confetti.min.js',
                '/learntotype/sounds/bell.wav',
                '/learntotype/sounds/error.wav',
                '/learntotype/sounds/success.wav',
                '/learntotype/sounds/success2.wav',
                '/learntotype/Hebrew/images/Animals/Alligator.svg',
'/learntotype/Hebrew/images/Animals/Ant.svg',
'/learntotype/Hebrew/images/Animals/Bat.svg',
'/learntotype/Hebrew/images/Animals/Bear.svg',
'/learntotype/Hebrew/images/Animals/Beetle.svg',
'/learntotype/Hebrew/images/Animals/Bird.svg',
'/learntotype/Hebrew/images/Animals/Bumblebee.svg',
'/learntotype/Hebrew/images/Animals/Butterfly.svg',
'/learntotype/Hebrew/images/Animals/Cat.svg',
'/learntotype/Hebrew/images/Animals/Chick.svg',
'/learntotype/Hebrew/images/Animals/Cricket.svg',
'/learntotype/Hebrew/images/Animals/Dinosaur.svg',
'/learntotype/Hebrew/images/Animals/Dog.svg',
'/learntotype/Hebrew/images/Animals/Dolphin.svg',
'/learntotype/Hebrew/images/Animals/Dragon.svg',
'/learntotype/Hebrew/images/Animals/Duck.svg',
'/learntotype/Hebrew/images/Animals/Fish.svg',
'/learntotype/Hebrew/images/Animals/Flamingo.svg',
'/learntotype/Hebrew/images/Animals/Fox.svg',
'/learntotype/Hebrew/images/Animals/Frog.svg',
'/learntotype/Hebrew/images/Animals/Gorilla.svg',
'/learntotype/Hebrew/images/Animals/Hamster.svg',
'/learntotype/Hebrew/images/Animals/Hedgehog.svg',
'/learntotype/Hebrew/images/Animals/Hippopotamus.svg',
'/learntotype/Hebrew/images/Animals/Insect.svg',
'/learntotype/Hebrew/images/Animals/Kangaroo.svg',
'/learntotype/Hebrew/images/Animals/Koala.svg',
'/learntotype/Hebrew/images/Animals/Lizard.svg',
'/learntotype/Hebrew/images/Animals/Monkey.svg',
'/learntotype/Hebrew/images/Animals/Mosquito.svg',
'/learntotype/Hebrew/images/Animals/Mouse.svg',
'/learntotype/Hebrew/images/Animals/Octopus.svg',
'/learntotype/Hebrew/images/Animals/Orangutan.svg',
'/learntotype/Hebrew/images/Animals/Otter.svg',
'/learntotype/Hebrew/images/Animals/Owl.svg',
'/learntotype/Hebrew/images/Animals/Panda.svg',
'/learntotype/Hebrew/images/Animals/Parrot.svg',
'/learntotype/Hebrew/images/Animals/Peacock.svg',
'/learntotype/Hebrew/images/Animals/Penguin.svg',
'/learntotype/Hebrew/images/Animals/Pigeon.svg',
'/learntotype/Hebrew/images/Animals/Poodle.svg',
'/learntotype/Hebrew/images/Animals/Pufferfish.svg',
'/learntotype/Hebrew/images/Animals/Rabbit.svg',
'/learntotype/Hebrew/images/Animals/Raccoon.svg',
'/learntotype/Hebrew/images/Animals/Rat.svg',
'/learntotype/Hebrew/images/Animals/Rooster.svg',
'/learntotype/Hebrew/images/Animals/Scorpion.svg',
'/learntotype/Hebrew/images/Animals/Shark.svg',
'/learntotype/Hebrew/images/Animals/Skunk.svg',
'/learntotype/Hebrew/images/Animals/Sloth.svg',
'/learntotype/Hebrew/images/Animals/Snail.svg',
'/learntotype/Hebrew/images/Animals/Snake.svg',
'/learntotype/Hebrew/images/Animals/Spider.svg',
'/learntotype/Hebrew/images/Animals/Squirrel.svg',
'/learntotype/Hebrew/images/Animals/Swan.svg',
'/learntotype/Hebrew/images/Animals/Tiger.svg',
'/learntotype/Hebrew/images/Animals/Turkey.svg',
'/learntotype/Hebrew/images/Animals/Turtle.svg',
'/learntotype/Hebrew/images/Animals/Vultures.svg',
'/learntotype/Hebrew/images/Animals/Whale.svg',
'/learntotype/Hebrew/images/Animals/Wolf.svg',
'/learntotype/Hebrew/images/Body/Boy.svg',
'/learntotype/Hebrew/images/Body/Ear.svg',
'/learntotype/Hebrew/images/Body/Eyes.svg',
'/learntotype/Hebrew/images/Body/Fist.svg',
'/learntotype/Hebrew/images/Body/Foot.svg',
'/learntotype/Hebrew/images/Body/Girl.svg',
'/learntotype/Hebrew/images/Body/Hand.svg',
'/learntotype/Hebrew/images/Body/Heart.svg',
'/learntotype/Hebrew/images/Body/Mouth.svg',
'/learntotype/Hebrew/images/Body/Muscle.svg',
'/learntotype/Hebrew/images/Body/Nose.svg',
'/learntotype/Hebrew/images/Body/Okay.svg',
'/learntotype/Hebrew/images/Body/Tooth.svg',
'/learntotype/Hebrew/images/Body/Woman.svg',
'/learntotype/Hebrew/images/Clothes/Bag.svg',
'/learntotype/Hebrew/images/Clothes/Ballet shoes.svg',
'/learntotype/Hebrew/images/Clothes/Binoculars.svg',
'/learntotype/Hebrew/images/Clothes/Coat.svg',
'/learntotype/Hebrew/images/Clothes/Crown.svg',
'/learntotype/Hebrew/images/Clothes/Dress.svg',
'/learntotype/Hebrew/images/Clothes/Flip flops.svg',
'/learntotype/Hebrew/images/Clothes/Glasses.svg',
'/learntotype/Hebrew/images/Clothes/Glove.svg',
'/learntotype/Hebrew/images/Clothes/Hat.svg',
'/learntotype/Hebrew/images/Clothes/Helmet.svg',
'/learntotype/Hebrew/images/Clothes/Jeans.svg',
'/learntotype/Hebrew/images/Clothes/Lipstick.svg',
"/learntotype/Hebrew/images/Clothes/Magician's hat.svg",
'/learntotype/Hebrew/images/Clothes/Pants.svg',
'/learntotype/Hebrew/images/Clothes/Purse.svg',
'/learntotype/Hebrew/images/Clothes/Ring.svg',
'/learntotype/Hebrew/images/Clothes/Running shoe.svg',
'/learntotype/Hebrew/images/Clothes/Scarf.svg',
'/learntotype/Hebrew/images/Clothes/School bag.svg',
'/learntotype/Hebrew/images/Clothes/Shoe.svg',
'/learntotype/Hebrew/images/Clothes/Snowman.svg',
'/learntotype/Hebrew/images/Clothes/Socks.svg',
'/learntotype/Hebrew/images/Clothes/Sunglasses.svg',
'/learntotype/Hebrew/images/Clothes/Underpants.svg',
'/learntotype/Hebrew/images/Clothes/Walking shoe.svg',
"/learntotype/Hebrew/images/Clothes/Woman's shoe.svg",
'/learntotype/Hebrew/images/Emotions/Afraid.svg',
'/learntotype/Hebrew/images/Emotions/Angry.svg',
'/learntotype/Hebrew/images/Emotions/Applause.svg',
'/learntotype/Hebrew/images/Emotions/Cold.svg',
'/learntotype/Hebrew/images/Emotions/Crying.svg',
'/learntotype/Hebrew/images/Emotions/Down.svg',
'/learntotype/Hebrew/images/Emotions/Forbidden.svg',
'/learntotype/Hebrew/images/Emotions/Handshake.svg',
'/learntotype/Hebrew/images/Emotions/Kiss.svg',
'/learntotype/Hebrew/images/Emotions/Left.svg',
'/learntotype/Hebrew/images/Emotions/Question mark.svg',
'/learntotype/Hebrew/images/Emotions/Right.svg',
'/learntotype/Hebrew/images/Emotions/Sick.svg',
'/learntotype/Hebrew/images/Emotions/Sleep.svg',
'/learntotype/Hebrew/images/Emotions/Sneeze.svg',
'/learntotype/Hebrew/images/Emotions/Surprised.svg',
'/learntotype/Hebrew/images/Emotions/Up.svg',
'/learntotype/Hebrew/images/Emotions/Warning.svg',
'/learntotype/Hebrew/images/Food/Apple.svg',
'/learntotype/Hebrew/images/Food/Avocado.svg',
'/learntotype/Hebrew/images/Food/Baguette.svg',
'/learntotype/Hebrew/images/Food/Banana.svg',
'/learntotype/Hebrew/images/Food/Beer.svg',
'/learntotype/Hebrew/images/Food/Bottle.svg',
'/learntotype/Hebrew/images/Food/Bowl.svg',
'/learntotype/Hebrew/images/Food/Bread.svg',
'/learntotype/Hebrew/images/Food/Broccoli.svg',
'/learntotype/Hebrew/images/Food/Burrito.svg',
'/learntotype/Hebrew/images/Food/Butter.svg',
'/learntotype/Hebrew/images/Food/Candy.svg',
'/learntotype/Hebrew/images/Food/Carrot.svg',
'/learntotype/Hebrew/images/Food/Champagne.svg',
'/learntotype/Hebrew/images/Food/Cheese.svg',
'/learntotype/Hebrew/images/Food/Cherries.svg',
'/learntotype/Hebrew/images/Food/Chestnuts.svg',
'/learntotype/Hebrew/images/Food/Chicken.svg',
'/learntotype/Hebrew/images/Food/Chocolate.svg',
'/learntotype/Hebrew/images/Food/Coconut.svg',
'/learntotype/Hebrew/images/Food/Coffee.svg',
'/learntotype/Hebrew/images/Food/Cookie.svg',
'/learntotype/Hebrew/images/Food/Corn.svg',
'/learntotype/Hebrew/images/Food/Croissant.svg',
'/learntotype/Hebrew/images/Food/Cucumber.svg',
'/learntotype/Hebrew/images/Food/Cupcake.svg',
'/learntotype/Hebrew/images/Food/Dessert.svg',
'/learntotype/Hebrew/images/Food/Doughnut.svg',
'/learntotype/Hebrew/images/Food/Drink.svg',
'/learntotype/Hebrew/images/Food/Egg.svg',
'/learntotype/Hebrew/images/Food/Eggplant.svg',
'/learntotype/Hebrew/images/Food/Falafel.svg',
'/learntotype/Hebrew/images/Food/Fried egg.svg',
'/learntotype/Hebrew/images/Food/Fries.svg',
'/learntotype/Hebrew/images/Food/Garlic.svg',
'/learntotype/Hebrew/images/Food/Grapes.svg',
'/learntotype/Hebrew/images/Food/Hamburger.svg',
'/learntotype/Hebrew/images/Food/Honey.svg',
'/learntotype/Hebrew/images/Food/Hot dog.svg',
'/learntotype/Hebrew/images/Food/Hot pepper.svg',
'/learntotype/Hebrew/images/Food/Ice cream.svg',
'/learntotype/Hebrew/images/Food/Juice.svg',
'/learntotype/Hebrew/images/Food/Kiwi.svg',
'/learntotype/Hebrew/images/Food/Knife and fork.svg',
'/learntotype/Hebrew/images/Food/Knife.svg',
'/learntotype/Hebrew/images/Food/Lemon.svg',
'/learntotype/Hebrew/images/Food/Lettuce.svg',
'/learntotype/Hebrew/images/Food/Mango.svg',
'/learntotype/Hebrew/images/Food/Meat.svg',
'/learntotype/Hebrew/images/Food/Melon.svg',
'/learntotype/Hebrew/images/Food/Milk.svg',
'/learntotype/Hebrew/images/Food/Onion.svg',
'/learntotype/Hebrew/images/Food/Orange.svg',
'/learntotype/Hebrew/images/Food/Pancake.svg',
'/learntotype/Hebrew/images/Food/Peach.svg',
'/learntotype/Hebrew/images/Food/Peanut.svg',
'/learntotype/Hebrew/images/Food/Pear.svg',
'/learntotype/Hebrew/images/Food/Pie.svg',
'/learntotype/Hebrew/images/Food/Pineapple.svg',
'/learntotype/Hebrew/images/Food/Pita.svg',
'/learntotype/Hebrew/images/Food/Pizza.svg',
'/learntotype/Hebrew/images/Food/Plate.svg',
'/learntotype/Hebrew/images/Food/Popcorn.svg',
'/learntotype/Hebrew/images/Food/Potato.svg',
'/learntotype/Hebrew/images/Food/Pretzels.svg',
'/learntotype/Hebrew/images/Food/Salad.svg',
'/learntotype/Hebrew/images/Food/Salt.svg',
'/learntotype/Hebrew/images/Food/Sandwich.svg',
'/learntotype/Hebrew/images/Food/Strawberry.svg',
'/learntotype/Hebrew/images/Food/Taco.svg',
'/learntotype/Hebrew/images/Food/Tea.svg',
'/learntotype/Hebrew/images/Food/Teaspoon.svg',
'/learntotype/Hebrew/images/Food/Tin can.svg',
'/learntotype/Hebrew/images/Food/Tomato.svg',
'/learntotype/Hebrew/images/Food/Waffle.svg',
'/learntotype/Hebrew/images/Food/Watermelon.svg',
'/learntotype/Hebrew/images/Food/Whiskey.svg',
'/learntotype/Hebrew/images/Food/Wine.svg',
'/learntotype/Hebrew/images/Home/Bathroom.svg',
'/learntotype/Hebrew/images/Home/Bed.svg',
'/learntotype/Hebrew/images/Home/Book.svg',
'/learntotype/Hebrew/images/Home/Books.svg',
'/learntotype/Hebrew/images/Home/Bricks.svg',
'/learntotype/Hebrew/images/Home/Candle.svg',
'/learntotype/Hebrew/images/Home/Chair.svg',
'/learntotype/Hebrew/images/Home/Computer.svg',
'/learntotype/Hebrew/images/Home/Disc.svg',
'/learntotype/Hebrew/images/Home/Door.svg',
'/learntotype/Hebrew/images/Home/Headphones.svg',
'/learntotype/Hebrew/images/Home/Image.svg',
'/learntotype/Hebrew/images/Home/Lamp.svg',
'/learntotype/Hebrew/images/Home/Lotion.svg',
'/learntotype/Hebrew/images/Home/Newspaper.svg',
'/learntotype/Hebrew/images/Home/Phone.svg',
'/learntotype/Hebrew/images/Home/Plug.svg',
'/learntotype/Hebrew/images/Home/Radio.svg',
'/learntotype/Hebrew/images/Home/Razor.svg',
'/learntotype/Hebrew/images/Home/Screen.svg',
'/learntotype/Hebrew/images/Home/Shower.svg',
'/learntotype/Hebrew/images/Home/Soap.svg',
'/learntotype/Hebrew/images/Home/Sofa.svg',
'/learntotype/Hebrew/images/Home/Sponge.svg',
'/learntotype/Hebrew/images/Home/Television.svg',
'/learntotype/Hebrew/images/Home/Toilet paper.svg',
'/learntotype/Hebrew/images/Home/Toilet.svg',
'/learntotype/Hebrew/images/Musical instruments/Accordion.svg',
'/learntotype/Hebrew/images/Musical instruments/Drum.svg',
'/learntotype/Hebrew/images/Musical instruments/French horn.svg',
'/learntotype/Hebrew/images/Musical instruments/Guitar.svg',
'/learntotype/Hebrew/images/Musical instruments/Saxophone.svg',
'/learntotype/Hebrew/images/Musical instruments/Trumpet.svg',
'/learntotype/Hebrew/images/Musical instruments/Violin.svg',
'/learntotype/Hebrew/images/Numbers/-100.svg',
'/learntotype/Hebrew/images/Numbers/0.svg',
'/learntotype/Hebrew/images/Numbers/1.svg',
'/learntotype/Hebrew/images/Numbers/10.svg',
'/learntotype/Hebrew/images/Numbers/100.svg',
'/learntotype/Hebrew/images/Numbers/11.svg',
'/learntotype/Hebrew/images/Numbers/12.svg',
'/learntotype/Hebrew/images/Numbers/13.svg',
'/learntotype/Hebrew/images/Numbers/14.svg',
'/learntotype/Hebrew/images/Numbers/15.svg',
'/learntotype/Hebrew/images/Numbers/16.svg',
'/learntotype/Hebrew/images/Numbers/17.svg',
'/learntotype/Hebrew/images/Numbers/18.svg',
'/learntotype/Hebrew/images/Numbers/19.svg',
'/learntotype/Hebrew/images/Numbers/2.svg',
'/learntotype/Hebrew/images/Numbers/20.svg',
'/learntotype/Hebrew/images/Numbers/3.svg',
'/learntotype/Hebrew/images/Numbers/30.svg',
'/learntotype/Hebrew/images/Numbers/4.svg',
'/learntotype/Hebrew/images/Numbers/40.svg',
'/learntotype/Hebrew/images/Numbers/5.svg',
'/learntotype/Hebrew/images/Numbers/50.svg',
'/learntotype/Hebrew/images/Numbers/6.svg',
'/learntotype/Hebrew/images/Numbers/60.svg',
'/learntotype/Hebrew/images/Numbers/7.svg',
'/learntotype/Hebrew/images/Numbers/70.svg',
'/learntotype/Hebrew/images/Numbers/8.svg',
'/learntotype/Hebrew/images/Numbers/80.svg',
'/learntotype/Hebrew/images/Numbers/9.svg',
'/learntotype/Hebrew/images/Numbers/90.svg',
'/learntotype/Hebrew/images/People/Astronaut.svg',
'/learntotype/Hebrew/images/People/Baby.svg',
'/learntotype/Hebrew/images/People/Bride.svg',
'/learntotype/Hebrew/images/People/Chef.svg',
'/learntotype/Hebrew/images/People/Clown.svg',
'/learntotype/Hebrew/images/People/Constructor.svg',
'/learntotype/Hebrew/images/People/Detective.svg',
'/learntotype/Hebrew/images/People/Doctor.svg',
'/learntotype/Hebrew/images/People/Draw.svg',
'/learntotype/Hebrew/images/People/Elf.svg',
'/learntotype/Hebrew/images/People/Farmer.svg',
'/learntotype/Hebrew/images/People/Fireman.svg',
'/learntotype/Hebrew/images/People/Genie.svg',
'/learntotype/Hebrew/images/People/Ghost.svg',
'/learntotype/Hebrew/images/People/Grandfather.svg',
'/learntotype/Hebrew/images/People/Grandmother.svg',
'/learntotype/Hebrew/images/People/Judge.svg',
'/learntotype/Hebrew/images/People/Lab technician.svg',
'/learntotype/Hebrew/images/People/Magician.svg',
'/learntotype/Hebrew/images/People/Mother.svg',
'/learntotype/Hebrew/images/People/Prince.svg',
'/learntotype/Hebrew/images/People/Princess.svg',
'/learntotype/Hebrew/images/People/Santa claus.svg',
'/learntotype/Hebrew/images/People/Teacher.svg',
'/learntotype/Hebrew/images/People/Vampire.svg',
'/learntotype/Hebrew/images/People/Welder.svg',
'/learntotype/Hebrew/images/Places/Castle.svg',
'/learntotype/Hebrew/images/Places/Church.svg',
'/learntotype/Hebrew/images/Places/Circus.svg',
'/learntotype/Hebrew/images/Places/Factory.svg',
'/learntotype/Hebrew/images/Places/Ferris wheel.svg',
'/learntotype/Hebrew/images/Places/Home.svg',
'/learntotype/Hebrew/images/Places/Hospital.svg',
'/learntotype/Hebrew/images/Places/Hut.svg',
'/learntotype/Hebrew/images/Places/Island.svg',
'/learntotype/Hebrew/images/Places/Mosque.svg',
'/learntotype/Hebrew/images/Places/Mountain.svg',
'/learntotype/Hebrew/images/Places/Office.svg',
'/learntotype/Hebrew/images/Places/Roller coaster.svg',
'/learntotype/Hebrew/images/Places/School.svg',
'/learntotype/Hebrew/images/Places/Shop.svg',
'/learntotype/Hebrew/images/Places/Stadium.svg',
'/learntotype/Hebrew/images/Places/Statue of liberty.svg',
'/learntotype/Hebrew/images/Places/Synagogue.svg',
'/learntotype/Hebrew/images/Places/Tent.svg',
'/learntotype/Hebrew/images/Places/Volcano.svg',
'/learntotype/Hebrew/images/Plants/Cactus.svg',
'/learntotype/Hebrew/images/Plants/Flower.svg',
'/learntotype/Hebrew/images/Plants/Flowers.svg',
'/learntotype/Hebrew/images/Plants/Hibiscus flower.svg',
'/learntotype/Hebrew/images/Plants/Leaf.svg',
'/learntotype/Hebrew/images/Plants/Maple leaf.svg',
'/learntotype/Hebrew/images/Plants/Mushroom.svg',
'/learntotype/Hebrew/images/Plants/Rose.svg',
'/learntotype/Hebrew/images/Plants/Sunflower.svg',
'/learntotype/Hebrew/images/Plants/Tree.svg',
'/learntotype/Hebrew/images/Plants/Tulip.svg',
'/learntotype/Hebrew/images/Sport/Baseball.svg',
'/learntotype/Hebrew/images/Sport/Basketball.svg',
'/learntotype/Hebrew/images/Sport/Bowling.svg',
'/learntotype/Hebrew/images/Sport/First place.svg',
'/learntotype/Hebrew/images/Sport/Football.svg',
'/learntotype/Hebrew/images/Sport/Gate.svg',
'/learntotype/Hebrew/images/Sport/Hockey.svg',
'/learntotype/Hebrew/images/Sport/Medal.svg',
'/learntotype/Hebrew/images/Sport/Ping pong.svg',
'/learntotype/Hebrew/images/Sport/Second place.svg',
'/learntotype/Hebrew/images/Sport/Tennis ball.svg',
'/learntotype/Hebrew/images/Sport/Third place.svg',
'/learntotype/Hebrew/images/Sport/Trophy.svg',
'/learntotype/Hebrew/images/Sport/Volleyball.svg',
'/learntotype/Hebrew/images/Stuff/Abacus.svg',
'/learntotype/Hebrew/images/Stuff/Anchor.svg',
'/learntotype/Hebrew/images/Stuff/Bacteria.svg',
'/learntotype/Hebrew/images/Stuff/Bags.svg',
'/learntotype/Hebrew/images/Stuff/Ball.svg',
'/learntotype/Hebrew/images/Stuff/Balloon.svg',
'/learntotype/Hebrew/images/Stuff/Barrel.svg',
'/learntotype/Hebrew/images/Stuff/Battery.svg',
'/learntotype/Hebrew/images/Stuff/Bell.svg',
'/learntotype/Hebrew/images/Stuff/Bomb.svg',
'/learntotype/Hebrew/images/Stuff/Bone.svg',
'/learntotype/Hebrew/images/Stuff/Bow tie.svg',
'/learntotype/Hebrew/images/Stuff/Chain.svg',
'/learntotype/Hebrew/images/Stuff/Cloud.svg',
'/learntotype/Hebrew/images/Stuff/Cobwebs.svg',
'/learntotype/Hebrew/images/Stuff/Coin.svg',
'/learntotype/Hebrew/images/Stuff/Diamond.svg',
'/learntotype/Hebrew/images/Stuff/Drop.svg',
'/learntotype/Hebrew/images/Stuff/Earth.svg',
'/learntotype/Hebrew/images/Stuff/Explosion.svg',
'/learntotype/Hebrew/images/Stuff/Fire.svg',
'/learntotype/Hebrew/images/Stuff/Fireworks.svg',
'/learntotype/Hebrew/images/Stuff/Fountain.svg',
'/learntotype/Hebrew/images/Stuff/Full moon.svg',
'/learntotype/Hebrew/images/Stuff/Ice.svg',
'/learntotype/Hebrew/images/Stuff/Lightning.svg',
'/learntotype/Hebrew/images/Stuff/Log.svg',
'/learntotype/Hebrew/images/Stuff/Map.svg',
'/learntotype/Hebrew/images/Stuff/Meteor.svg',
'/learntotype/Hebrew/images/Stuff/Money.svg',
'/learntotype/Hebrew/images/Stuff/Moon.svg',
'/learntotype/Hebrew/images/Stuff/Page.svg',
'/learntotype/Hebrew/images/Stuff/Parachute.svg',
'/learntotype/Hebrew/images/Stuff/Projector.svg',
'/learntotype/Hebrew/images/Stuff/Receipt.svg',
'/learntotype/Hebrew/images/Stuff/Scales.svg',
'/learntotype/Hebrew/images/Stuff/Scroll.svg',
'/learntotype/Hebrew/images/Stuff/Shell.svg',
'/learntotype/Hebrew/images/Stuff/Shopping cart.svg',
'/learntotype/Hebrew/images/Stuff/Siren.svg',
'/learntotype/Hebrew/images/Stuff/Snowflake.svg',
'/learntotype/Hebrew/images/Stuff/Star.svg',
'/learntotype/Hebrew/images/Stuff/Stone.svg',
'/learntotype/Hebrew/images/Stuff/Stopwatch.svg',
'/learntotype/Hebrew/images/Stuff/Suitcase.svg',
'/learntotype/Hebrew/images/Stuff/Tornado.svg',
'/learntotype/Hebrew/images/Stuff/Traffic lights.svg',
'/learntotype/Hebrew/images/Tools/Alarm clock.svg',
'/learntotype/Hebrew/images/Tools/Axe.svg',
'/learntotype/Hebrew/images/Tools/Basket.svg',
'/learntotype/Hebrew/images/Tools/Bow and arrow.svg',
'/learntotype/Hebrew/images/Tools/Broom.svg',
'/learntotype/Hebrew/images/Tools/Camera.svg',
'/learntotype/Hebrew/images/Tools/Colors.svg',
'/learntotype/Hebrew/images/Tools/Compass.svg',
'/learntotype/Hebrew/images/Tools/Dagger.svg',
'/learntotype/Hebrew/images/Tools/Fire extinguisher.svg',
'/learntotype/Hebrew/images/Tools/Flashlight.svg',
'/learntotype/Hebrew/images/Tools/Hammer.svg',
'/learntotype/Hebrew/images/Tools/Hourglass.svg',
'/learntotype/Hebrew/images/Tools/Jug.svg',
'/learntotype/Hebrew/images/Tools/Key.svg',
'/learntotype/Hebrew/images/Tools/Lock.svg',
'/learntotype/Hebrew/images/Tools/Magnet.svg',
'/learntotype/Hebrew/images/Tools/Magnifying glass.svg',
'/learntotype/Hebrew/images/Tools/Megaphone.svg',
'/learntotype/Hebrew/images/Tools/Microphone.svg',
'/learntotype/Hebrew/images/Tools/Pick.svg',
'/learntotype/Hebrew/images/Tools/Plaster.svg',
'/learntotype/Hebrew/images/Tools/Printer.svg',
'/learntotype/Hebrew/images/Tools/Safety pin.svg',
'/learntotype/Hebrew/images/Tools/Shield.svg',
'/learntotype/Hebrew/images/Tools/Stethoscope.svg',
'/learntotype/Hebrew/images/Tools/Swords.svg',
'/learntotype/Hebrew/images/Tools/Syringe.svg',
'/learntotype/Hebrew/images/Tools/Test tube.svg',
'/learntotype/Hebrew/images/Tools/Thermometer.svg',
'/learntotype/Hebrew/images/Tools/Toolbox.svg',
'/learntotype/Hebrew/images/Tools/Umbrella.svg',
'/learntotype/Hebrew/images/Tools/Vest.svg',
'/learntotype/Hebrew/images/Tools/Watch.svg',
'/learntotype/Hebrew/images/Tools/Wire.svg',
'/learntotype/Hebrew/images/Tools/Wrench.svg',
'/learntotype/Hebrew/images/Transportation/Airplane.svg',
'/learntotype/Hebrew/images/Transportation/Ambulance.svg',
'/learntotype/Hebrew/images/Transportation/Bicycle.svg',
'/learntotype/Hebrew/images/Transportation/Boat.svg',
'/learntotype/Hebrew/images/Transportation/Bus.svg',
'/learntotype/Hebrew/images/Transportation/Cab.svg',
'/learntotype/Hebrew/images/Transportation/Canoe.svg',
'/learntotype/Hebrew/images/Transportation/Car.svg',
'/learntotype/Hebrew/images/Transportation/Fire truck.svg',
'/learntotype/Hebrew/images/Transportation/Fuel.svg',
'/learntotype/Hebrew/images/Transportation/Locomotive.svg',
'/learntotype/Hebrew/images/Transportation/Moped.svg',
'/learntotype/Hebrew/images/Transportation/Motorcycle.svg',
'/learntotype/Hebrew/images/Transportation/Plane.svg',
'/learntotype/Hebrew/images/Transportation/Police car.svg',
'/learntotype/Hebrew/images/Transportation/Race car.svg',
'/learntotype/Hebrew/images/Transportation/Sailboat.svg',
'/learntotype/Hebrew/images/Transportation/Scooter.svg',
'/learntotype/Hebrew/images/Transportation/Skateboard.svg',
'/learntotype/Hebrew/images/Transportation/Speedboat.svg',
'/learntotype/Hebrew/images/Transportation/Tractor.svg',
'/learntotype/Hebrew/images/Transportation/Truck.svg',
'/learntotype/Hebrew/images/Transportation/Wheelchair.svg'
            ]);
        })
    );
});

self.addEventListener('fetch', function(event) {
    event.respondWith(
        caches.match(event.request).then(function(response) {
            return response || fetch(event.request);
        })
    );
});